# Generated by Django 4.2.4 on 2023-09-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birth_data_profile_social_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
