# Generated by Django 4.2.4 on 2023-09-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_addressprovince_address_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressCity',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='AddressProvince',
            new_name='Province',
        ),
    ]
