# Generated by Django 4.2.4 on 2023-09-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_addresscity_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
